GET https://puhelinluettelo-fullstack-qbp1.onrender.com/

###

GET https://puhelinluettelo-fullstack-qbp1.onrender.com/info

###
GET https://puhelinluettelo-fullstack-qbp1.onrender.com/api/persons

###

GET https://puhelinluettelo-fullstack-qbp1.onrender.com/api/persons/1