POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "RATTYMCRAT",
    "number": "44444444"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "CAT"
}   

###

POST http://localhost:3001/api/persons
content-type: application/json

{}