POST https://puhelinluettelo-fullstack-qbp1.onrender.com/api/persons
content-type: application/json

{
    "name": "CAT",
    "number": "1231313"
}

###

POST https://puhelinluettelo-fullstack-qbp1.onrender.com/api/persons
content-type: application/json

{
    "name": "CAT"
}

###

POST https://puhelinluettelo-fullstack-qbp1.onrender.com/api/persons
content-type: application/json

{}